### ISSUE TITLE
java 11 

### ISSUE THREAD

**Issue by bmgante** [cetic/helm-nifi#229] opened 2022-02-04 15:29 UTC
Hello,
I am using this helm chart with nifi 1.12.1 and would like to know if it is possible to use java 11 instead java 8 and how to do that.
Also, would like to know if you are aware of any limitation when using java 11 for this nifi version.

Thanks

**Comment by banzo** [comment] 2022-02-16 11:36
duplicate of #85

**Closed by banzo** 2022-02-16 11:36 UTC
Labels: duplicate
